// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtTOpSxAfAc2qJjHYxoAcIefWd0boZ9vM',
    appId: '1:183953544834:web:e778e5c794501aa4e7469b',
    messagingSenderId: '183953544834',
    projectId: 'trader-bb666',
    authDomain: 'trader-bb666.firebaseapp.com',
    storageBucket: 'trader-bb666.appspot.com',
    measurementId: 'G-DK2Q421WM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIeS2nFcaJLdC0asxrv1ZJ1i5Qc_kWKqg',
    appId: '1:183953544834:android:f58c586099f4aa3be7469b',
    messagingSenderId: '183953544834',
    projectId: 'trader-bb666',
    storageBucket: 'trader-bb666.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrY7RPGi6iRWhHh7SNwENV2EV-wR748dA',
    appId: '1:183953544834:ios:9588c523b9beb751e7469b',
    messagingSenderId: '183953544834',
    projectId: 'trader-bb666',
    storageBucket: 'trader-bb666.appspot.com',
    iosBundleId: 'com.example.traderapp',
  );
}
